"""Initial schema

Revision ID: 95c749193f65
Revises: 
Create Date: 2026-06-09 16:08:18.752125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95c749193f65'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == "sqlite"
    default_now = sa.text("CURRENT_TIMESTAMP") if is_sqlite else sa.text("timezone('utc'::text, now())")
    uuid_type = sa.String(36) if is_sqlite else sa.UUID()

    op.create_table('hogares',
    sa.Column('id', uuid_type, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=default_now, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=default_now, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventos_calendario',
    sa.Column('id', uuid_type, nullable=False),
    sa.Column('hogar_id', uuid_type, nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('participantes', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=default_now, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=default_now, nullable=False),
    sa.ForeignKeyConstraint(['hogar_id'], ['hogares.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_calendario_hogar_id'), 'eventos_calendario', ['hogar_id'], unique=False)
    op.create_index(op.f('ix_eventos_calendario_is_deleted'), 'eventos_calendario', ['is_deleted'], unique=False)
    op.create_table('inventario_alimentos',
    sa.Column('id', uuid_type, nullable=False),
    sa.Column('hogar_id', uuid_type, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unidad', sa.String(length=30), nullable=False),
    sa.Column('fecha_caducidad', sa.Date(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=default_now, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=default_now, nullable=False),
    sa.ForeignKeyConstraint(['hogar_id'], ['hogares.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventario_alimentos_hogar_id'), 'inventario_alimentos', ['hogar_id'], unique=False)
    op.create_index(op.f('ix_inventario_alimentos_is_deleted'), 'inventario_alimentos', ['is_deleted'], unique=False)
    op.create_table('tareas_hogar',
    sa.Column('id', uuid_type, nullable=False),
    sa.Column('hogar_id', uuid_type, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('asignado_a', sa.String(length=100), nullable=True),
    sa.Column('frecuencia', sa.String(length=50), nullable=False),
    sa.Column('ultimo_completado', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=default_now, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=default_now, nullable=False),
    sa.ForeignKeyConstraint(['hogar_id'], ['hogares.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tareas_hogar_hogar_id'), 'tareas_hogar', ['hogar_id'], unique=False)
    op.create_index(op.f('ix_tareas_hogar_is_deleted'), 'tareas_hogar', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tareas_hogar_is_deleted'), table_name='tareas_hogar')
    op.drop_index(op.f('ix_tareas_hogar_hogar_id'), table_name='tareas_hogar')
    op.drop_table('tareas_hogar')
    op.drop_index(op.f('ix_inventario_alimentos_is_deleted'), table_name='inventario_alimentos')
    op.drop_index(op.f('ix_inventario_alimentos_hogar_id'), table_name='inventario_alimentos')
    op.drop_table('inventario_alimentos')
    op.drop_index(op.f('ix_eventos_calendario_is_deleted'), table_name='eventos_calendario')
    op.drop_index(op.f('ix_eventos_calendario_hogar_id'), table_name='eventos_calendario')
    op.drop_table('eventos_calendario')
    op.drop_table('hogares')
    # ### end Alembic commands ###
